CREATE (lc:LexicalConcept:Noun {subject: 'noun.communication', partOfSpeech: 'Noun', definition: 'computer software released under a license restricting use, study or redistribution', uri: 'https://custom.extension/id/15349-n', example: ['the use of proprietary software is not allowed in our organization']})
CREATE (ls1:LexicalSense {uri: 'https://custom.extension/lemma/prop-soft#15349'})
CREATE (lc)<-[:isLexicalizedSenseOf]-(ls1)
CREATE (le1:LexicalEntry:Noun {canonicalForm: 'proprietary software', partOfSpeech: 'Noun', uri: 'https://custom.extension/lemma/prop-soft#prop-soft-n'})
CREATE (ls1)<-[:sense]-(le1)
CREATE (f1:Form {writtenRep: 'proprietary software', uri: 'https://custom.extension/lemma/prop-soft'})
CREATE (le1)-[:canonicalForm]->(f1)
CREATE (ls2:LexicalSense {uri: 'https://custom.extension/lemma/closed-soft#15348'})
CREATE (lc)<-[:isLexicalizedSenseOf]-(ls2)
CREATE (le2:LexicalEntry:Noun {canonicalForm: 'closed-source software', partOfSpeech: 'Noun', uri: 'https://custom.extension/lemma/closed-soft#closed-soft-n'})
CREATE (ls2)<-[:sense]-(le2)
CREATE (f2:Form {writtenRep: 'closed-source software', uri: 'https://custom.extension/lemma/closed-soft'})
CREATE (le2)-[:canonicalForm]->(f2)